# DB Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    name: db-service
  selector:
    app: db
  type: ClusterIP
status:
  loadBalancer: {}